#!/bin/bash

# Start with a blank line for clarity
echo ""

# System Information
echo "====================================="
echo " System Report generated by $USER "
echo " Date: $(date) "
echo "====================================="
echo ""
echo "System Information"
echo "-------------------"
echo "Hostname: $(hostname)"
source /etc/os-release
echo "Operating System: $NAME"
echo "Version: $VERSION"
echo "Uptime: $(uptime -p)"
echo ""

# Hardware Information
echo "Hardware Information"
echo "--------------------"
processor_make_model=$(lscpu | grep "Model name:" | awk -F ': ' '{print $2}')
echo "CPU Model: $processor_make_model"
cpu_speeds=$(sudo lshw -class processor | grep -m 1 -A 3 "size:" | awk '{print $2}' | xargs)
echo "CPU Speed: $cpu_speeds"
echo "Total RAM: $(free -h | awk '/Mem:/ {print $2}')"
echo "Disk Information:"
lsblk -o NAME,SIZE,MODEL --noheadings | grep -v "loop" | awk '{print "  Disk: " $1 ", Size: " $2 ", Model: " $3}'
video_info=$(lspci -v | grep -i "VGA compatible controller" | awk -F: '{print $3}')
echo "Video Card: $video_info"
echo ""

# Network Information
echo "Network Information"
echo "-------------------"
echo "FQDN: $(hostname --fqdn)"
echo "Host IP Address: $(hostname -I | awk '{print $1}')"
default_gateway=$(ip r | awk '$1 == "default" {print $3}')
echo "Default Gateway: $default_gateway"
echo "DNS Server(s) IP:"
grep "nameserver" /etc/resolv.conf | awk '{print "  " $2}'
echo ""
echo "Network Card Information:"
sudo lshw -class network | awk '/description: (Ethernet|Wireless interface)/ || /product:/ {print "  " $0}'
echo ""
echo "IP Address: $(ip -4 addr show | awk '/inet / {print $2}' | head -n 1)"
echo "CIDR Format: $(ip -4 addr show | awk '/inet / {print $2}' | head -n 1)"
echo ""

# System Status
echo "System Status"
echo "-------------"
echo "Users Logged In: $(who | awk '{users = users $1 ","} END {sub(/,$/, "", users); print users}')"
echo "Disk Space:"
df -h --output=target,avail | awk 'NR>1 {print "  " $1 ": " $2 " available"}'
echo "Process Count: $(($(ps -e | wc -l) - 1))"
echo "Load Averages: $(uptime | awk -F'load average: ' '{print $2}')"
echo "Memory Usage: $(free -h | awk 'NR==2{print $3}')"
echo "Listening Network Ports: $(ss -lntu | awk 'NR>1 {print $5}' | awk -F':' '{print $NF}' | sort | uniq | xargs)"
echo "UFW Rules:"
sudo ufw status numbered | awk '{print "  " $0}'
echo ""
